import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ControlItem } from '@/types';
import { AUREUM_LOGO_BASE64 } from '@/assets/aureumLogoBase64';

export interface DocumentSections {
  cover: boolean;
  toc: boolean;
  executiveSummary: boolean;
  projectOverview: boolean;
  securityControls: boolean;
  annexA: boolean;
  annexB: boolean;
}

export const DEFAULT_SECTIONS: DocumentSections = {
  cover: true,
  toc: true,
  executiveSummary: true,
  projectOverview: true,
  securityControls: true,
  annexA: true,
  annexB: true,
};

interface DocumentOptions {
  projectName: string;
  technology: string;
  version: number;
  publishedAt?: string;
  locale: 'en' | 'pt' | 'es';
  controls: ControlItem[];
  sources?: any[];
  sections?: DocumentSections;
}

const CATEGORY_LABELS: Record<string, Record<string, string>> = {
  identity: { en: 'Identity & Access', pt: 'Identidade e Acesso', es: 'Identidad y Acceso' },
  encryption: { en: 'Encryption & Data Protection', pt: 'Criptografia e Proteção de Dados', es: 'Cifrado y Protección de Datos' },
  logging: { en: 'Logging & Monitoring', pt: 'Logs e Monitoramento', es: 'Logs y Monitoreo' },
  network: { en: 'Network Security', pt: 'Segurança de Rede', es: 'Seguridad de Red' },
  storage: { en: 'Storage & Resilience', pt: 'Armazenamento e Resiliência', es: 'Almacenamiento y Resiliencia' },
  runtime: { en: 'Runtime Security', pt: 'Segurança em Tempo de Execução', es: 'Seguridad en Tiempo de Ejecución' },
  cicd: { en: 'CI/CD & Supply Chain', pt: 'CI/CD e Cadeia de Suprimentos', es: 'CI/CD y Cadena de Suministro' },
};

const CATEGORY_ORDER = ['identity', 'encryption', 'network', 'logging', 'storage', 'runtime', 'cicd'];

const labels = {
  en: {
    title: 'Security Baseline Document',
    toc: 'Table of Contents',
    executiveSummary: 'Executive Summary',
    executiveSummaryBody: (opts: DocumentOptions) =>
      `This document presents the security baseline for ${opts.technology}, version ${opts.version}. It contains ${opts.controls.length} security controls organized by category, with framework mappings, threat modeling, and source traceability. The baseline was generated and reviewed using Aureum Baseline Studio.`,
    projectOverview: 'Project Overview',
    projectName: 'Project Name',
    technology: 'Technology',
    version: 'Version',
    totalControls: 'Total Controls',
    publishedDate: 'Published Date',
    securityControls: 'Security Controls',
    controlId: 'Control ID',
    description: 'Description',
    applicability: 'Applicability',
    securityRisk: 'Security Risk',
    defaultBehavior: 'Default Behavior / Limitations',
    automation: 'Automation / Guardrail',
    criticality: 'Criticality',
    confidence: 'Confidence Score',
    reviewStatus: 'Review Status',
    frameworkMappings: 'Framework Mappings',
    threatModeling: 'Threat Modeling',
    threatName: 'Threat',
    strideCategory: 'STRIDE Category',
    attackVector: 'Attack Vector',
    likelihood: 'Likelihood',
    impact: 'Impact',
    mitigations: 'Mitigations',
    sourceTraceability: 'Source Traceability',
    sourceName: 'Source',
    excerpt: 'Excerpt',
    sourceConfidence: 'Confidence',
    annexA: 'Annex A — Framework Coverage Summary',
    annexB: 'Annex B — Source Traceability Index',
    framework: 'Framework',
    controlCount: 'Controls Mapped',
    coveragePercent: 'Coverage %',
    generatedBy: 'Generated by Aureum Baseline Studio',
    confidential: 'CONFIDENTIAL',
    page: 'Page',
    noCategory: 'Other',
  },
  pt: {
    title: 'Documento de Baseline de Segurança',
    toc: 'Sumário',
    executiveSummary: 'Resumo Executivo',
    executiveSummaryBody: (opts: DocumentOptions) =>
      `Este documento apresenta o baseline de segurança para ${opts.technology}, versão ${opts.version}. Contém ${opts.controls.length} controles de segurança organizados por categoria, com mapeamentos de frameworks, modelagem de ameaças e rastreabilidade de fontes. O baseline foi gerado e revisado usando o Aureum Baseline Studio.`,
    projectOverview: 'Visão Geral do Projeto',
    projectName: 'Nome do Projeto',
    technology: 'Tecnologia',
    version: 'Versão',
    totalControls: 'Total de Controles',
    publishedDate: 'Data de Publicação',
    securityControls: 'Controles de Segurança',
    controlId: 'ID do Controle',
    description: 'Descrição',
    applicability: 'Aplicabilidade',
    securityRisk: 'Risco de Segurança',
    defaultBehavior: 'Comportamento Padrão / Limitações',
    automation: 'Automação / Guardrail',
    criticality: 'Criticidade',
    confidence: 'Score de Confiança',
    reviewStatus: 'Status de Revisão',
    frameworkMappings: 'Mapeamentos de Frameworks',
    threatModeling: 'Modelagem de Ameaças',
    threatName: 'Ameaça',
    strideCategory: 'Categoria STRIDE',
    attackVector: 'Vetor de Ataque',
    likelihood: 'Probabilidade',
    impact: 'Impacto',
    mitigations: 'Mitigações',
    sourceTraceability: 'Rastreabilidade de Fontes',
    sourceName: 'Fonte',
    excerpt: 'Trecho',
    sourceConfidence: 'Confiança',
    annexA: 'Anexo A — Resumo de Cobertura de Frameworks',
    annexB: 'Anexo B — Índice de Rastreabilidade de Fontes',
    framework: 'Framework',
    controlCount: 'Controles Mapeados',
    coveragePercent: 'Cobertura %',
    generatedBy: 'Gerado pelo Aureum Baseline Studio',
    confidential: 'CONFIDENCIAL',
    page: 'Página',
    noCategory: 'Outros',
  },
  es: {
    title: 'Documento de Baseline de Seguridad',
    toc: 'Índice',
    executiveSummary: 'Resumen Ejecutivo',
    executiveSummaryBody: (opts: DocumentOptions) =>
      `Este documento presenta el baseline de seguridad para ${opts.technology}, versión ${opts.version}. Contiene ${opts.controls.length} controles de seguridad organizados por categoría, con mapeos de frameworks, modelado de amenazas y trazabilidad de fuentes. El baseline fue generado y revisado usando Aureum Baseline Studio.`,
    projectOverview: 'Visión General del Proyecto',
    projectName: 'Nombre del Proyecto',
    technology: 'Tecnología',
    version: 'Versión',
    totalControls: 'Total de Controles',
    publishedDate: 'Fecha de Publicación',
    securityControls: 'Controles de Seguridad',
    controlId: 'ID del Control',
    description: 'Descripción',
    applicability: 'Aplicabilidad',
    securityRisk: 'Riesgo de Seguridad',
    defaultBehavior: 'Comportamiento Predeterminado / Limitaciones',
    automation: 'Automatización / Guardrail',
    criticality: 'Criticidad',
    confidence: 'Score de Confianza',
    reviewStatus: 'Estado de Revisión',
    frameworkMappings: 'Mapeos de Frameworks',
    threatModeling: 'Modelado de Amenazas',
    threatName: 'Amenaza',
    strideCategory: 'Categoría STRIDE',
    attackVector: 'Vector de Ataque',
    likelihood: 'Probabilidad',
    impact: 'Impacto',
    mitigations: 'Mitigaciones',
    sourceTraceability: 'Trazabilidad de Fuentes',
    sourceName: 'Fuente',
    excerpt: 'Extracto',
    sourceConfidence: 'Confianza',
    annexA: 'Anexo A — Resumen de Cobertura de Frameworks',
    annexB: 'Anexo B — Índice de Trazabilidad de Fuentes',
    framework: 'Framework',
    controlCount: 'Controles Mapeados',
    coveragePercent: 'Cobertura %',
    generatedBy: 'Generado por Aureum Baseline Studio',
    confidential: 'CONFIDENCIAL',
    page: 'Página',
    noCategory: 'Otros',
  },
};

function getCategoryLabel(cat: string, locale: string): string {
  return CATEGORY_LABELS[cat]?.[locale] || cat.charAt(0).toUpperCase() + cat.slice(1);
}

function groupByCategory(controls: ControlItem[]): { category: string; controls: ControlItem[] }[] {
  const groups: Record<string, ControlItem[]> = {};
  for (const c of controls) {
    const cat = c.category || 'other';
    if (!groups[cat]) groups[cat] = [];
    groups[cat].push(c);
  }
  return CATEGORY_ORDER
    .filter(cat => groups[cat]?.length)
    .map(cat => ({ category: cat, controls: groups[cat] }))
    .concat(
      Object.keys(groups)
        .filter(cat => !CATEGORY_ORDER.includes(cat))
        .map(cat => ({ category: cat, controls: groups[cat] }))
    );
}

function getFrameworkCoverage(controls: ControlItem[]) {
  const fwMap: Record<string, number> = {};
  for (const c of controls) {
    for (const m of c.frameworkMappings) {
      const prefix = m.split(' ')[0].split('-')[0];
      fwMap[prefix] = (fwMap[prefix] || 0) + 1;
    }
  }
  return Object.entries(fwMap).map(([fw, count]) => ({
    framework: fw,
    count,
    percent: Math.round((count / controls.length) * 100),
  }));
}

function getSourceIndex(controls: ControlItem[]) {
  const srcMap: Record<string, { name: string; controlIds: string[]; avgConf: number; total: number }> = {};
  for (const c of controls) {
    for (const s of c.sourceTraceability) {
      if (!srcMap[s.sourceName]) {
        srcMap[s.sourceName] = { name: s.sourceName, controlIds: [], avgConf: 0, total: 0 };
      }
      srcMap[s.sourceName].controlIds.push(c.controlId);
      srcMap[s.sourceName].avgConf += s.confidence;
      srcMap[s.sourceName].total += 1;
    }
  }
  return Object.values(srcMap).map(s => ({
    ...s,
    avgConf: s.total > 0 ? Math.round((s.avgConf / s.total) * 100) : 0,
  }));
}

export function generateBaselinePDF(opts: DocumentOptions): void {
  const l = labels[opts.locale] || labels.en;
  const sec = opts.sections || DEFAULT_SECTIONS;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 0;

  const PRIMARY: [number, number, number] = [109, 40, 217]; // #6d28d9
  const DARK: [number, number, number] = [26, 26, 46]; // #1a1a2e
  const GRAY: [number, number, number] = [100, 116, 139];
  const LIGHT_BG: [number, number, number] = [248, 250, 252];

  // Helper: add page footer
  const addFooter = (pageNum: number) => {
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(l.confidential, margin, pageH - 8);
    doc.text(`${l.page} ${pageNum}`, pageW - margin, pageH - 8, { align: 'right' });
    doc.text(l.generatedBy, pageW / 2, pageH - 8, { align: 'center' });
  };

  // Helper: check page break
  const checkPageBreak = (needed: number) => {
    if (y + needed > pageH - 20) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
      y = margin;
    }
  };

  const dateStr = opts.publishedAt
    ? new Date(opts.publishedAt).toLocaleDateString(opts.locale === 'pt' ? 'pt-BR' : opts.locale === 'es' ? 'es-ES' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString();
  const grouped = groupByCategory(opts.controls);
  let isFirstPage = true;

  const addNewPage = () => {
    if (!isFirstPage) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
    } else {
      isFirstPage = false;
    }
    y = margin;
  };

  // ─── COVER PAGE ───
  if (sec.cover) {
    doc.setFillColor(...DARK);
    doc.rect(0, 0, pageW, pageH, 'F');
    try {
      doc.addImage(AUREUM_LOGO_BASE64, 'PNG', pageW / 2 - 20, 50, 40, 40);
    } catch { /* logo optional */ }
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(28);
    doc.text(l.title, pageW / 2, 115, { align: 'center' });
    doc.setFontSize(16);
    doc.setTextColor(180, 180, 200);
    doc.text(opts.projectName, pageW / 2, 135, { align: 'center' });
    doc.setFontSize(12);
    doc.text(`${opts.technology} — v${opts.version}`, pageW / 2, 150, { align: 'center' });
    doc.setFontSize(10);
    doc.setTextColor(140, 140, 160);
    doc.text(dateStr, pageW / 2, 170, { align: 'center' });
    doc.setFontSize(8);
    doc.text(l.confidential, pageW / 2, pageH - 20, { align: 'center' });
    isFirstPage = false;
  }

  // ─── TABLE OF CONTENTS ───
  if (sec.toc) {
    addNewPage();
    doc.setTextColor(...DARK);
    doc.setFontSize(20);
    doc.text(l.toc, margin, y);
    y += 12;

    let sectionNum = 0;
    const tocItems: string[] = [];
    if (sec.executiveSummary) { sectionNum++; tocItems.push(`${sectionNum}. ${l.executiveSummary}`); }
    if (sec.projectOverview) { sectionNum++; tocItems.push(`${sectionNum}. ${l.projectOverview}`); }
    if (sec.securityControls) {
      sectionNum++;
      tocItems.push(`${sectionNum}. ${l.securityControls}`);
      grouped.forEach((g, i) => {
        tocItems.push(`   ${sectionNum}.${i + 1}. ${getCategoryLabel(g.category, opts.locale)} (${g.controls.length})`);
      });
    }
    if (sec.annexA) { sectionNum++; tocItems.push(`${sectionNum}. ${l.annexA}`); }
    if (sec.annexB) { sectionNum++; tocItems.push(`${sectionNum}. ${l.annexB}`); }

    doc.setFontSize(11);
    for (const item of tocItems) {
      const clr = item.startsWith('   ') ? GRAY : DARK;
      doc.setTextColor(clr[0], clr[1], clr[2]);
      doc.text(item, item.startsWith('   ') ? margin + 8 : margin, y);
      y += 7;
    }
    addFooter(doc.getNumberOfPages());
  }

  // ─── 1. EXECUTIVE SUMMARY ───
  let sn = 0; // dynamic section numbering
  if (sec.executiveSummary) {
    addNewPage();
    sn++;
    doc.setFontSize(18);
    doc.setTextColor(...PRIMARY);
    doc.text(`${sn}. ${l.executiveSummary}`, margin, y);
    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(...DARK);
    const summaryLines = doc.splitTextToSize(l.executiveSummaryBody(opts), contentW);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 5 + 10;
    const stats = [
      { label: l.totalControls, value: `${opts.controls.length}` },
      { label: l.criticality, value: `${opts.controls.filter(c => c.criticality === 'critical').length} critical` },
      { label: l.confidence, value: `${Math.round(opts.controls.reduce((s, c) => s + c.confidenceScore, 0) / (opts.controls.length || 1) * 100)}%` },
    ];
    doc.setFillColor(...LIGHT_BG);
    doc.roundedRect(margin, y, contentW, 20, 2, 2, 'F');
    const statW = contentW / stats.length;
    stats.forEach((stat, i) => {
      const sx = margin + statW * i + statW / 2;
      doc.setFontSize(14);
      doc.setTextColor(...PRIMARY);
      doc.text(stat.value, sx, y + 9, { align: 'center' });
      doc.setFontSize(7);
      doc.setTextColor(...GRAY);
      doc.text(stat.label, sx, y + 15, { align: 'center' });
    });
    y += 28;
    addFooter(doc.getNumberOfPages());
  }

  // ─── 2. PROJECT OVERVIEW ───
  if (sec.projectOverview) {
    addNewPage();
    sn++;
    doc.setFontSize(18);
    doc.setTextColor(...PRIMARY);
    doc.text(`${sn}. ${l.projectOverview}`, margin, y);
    y += 10;
    autoTable(doc, {
      startY: y,
      head: [],
      body: [
        [l.projectName, opts.projectName],
        [l.technology, opts.technology],
        [l.version, `v${opts.version}`],
        [l.totalControls, `${opts.controls.length}`],
        [l.publishedDate, dateStr],
      ],
      theme: 'grid',
      styles: { fontSize: 9, cellPadding: 4 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50, fillColor: LIGHT_BG as any },
        1: { cellWidth: contentW - 50 },
      },
      margin: { left: margin, right: margin },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
    addFooter(doc.getNumberOfPages());
  }

  // ─── 3. SECURITY CONTROLS ───
  if (sec.securityControls) {
    addNewPage();
    sn++;
    doc.setFontSize(18);
    doc.setTextColor(...PRIMARY);
    doc.text(`${sn}. ${l.securityControls}`, margin, y);
    y += 12;

    grouped.forEach((group, gi) => {
      checkPageBreak(30);
      doc.setFontSize(14);
      doc.setTextColor(...DARK);
      doc.text(`${sn}.${gi + 1}. ${getCategoryLabel(group.category, opts.locale)}`, margin, y);
      y += 8;

      group.controls.forEach((ctrl) => {
        checkPageBreak(60);
        doc.setFillColor(245, 243, 255);
        doc.roundedRect(margin, y, contentW, 8, 1, 1, 'F');
        doc.setFontSize(9);
        doc.setTextColor(...PRIMARY);
        doc.text(ctrl.controlId, margin + 3, y + 5.5);
        doc.setTextColor(...DARK);
        doc.setFont(undefined!, 'bold');
        doc.text(ctrl.title, margin + 30, y + 5.5);
        doc.setFont(undefined!, 'normal');
        const critColors: Record<string, [number, number, number]> = {
          critical: [220, 38, 38], high: [234, 88, 12], medium: [202, 138, 4], low: [22, 163, 74],
        };
        const cc = critColors[ctrl.criticality] || GRAY;
        doc.setTextColor(...cc);
        doc.text(ctrl.criticality.toUpperCase(), pageW - margin - 3, y + 5.5, { align: 'right' });
        y += 12;

        const detailRows: string[][] = [];
        if (ctrl.description) detailRows.push([l.description, ctrl.description]);
        if (ctrl.applicability) detailRows.push([l.applicability, ctrl.applicability]);
        if (ctrl.securityRisk) detailRows.push([l.securityRisk, ctrl.securityRisk]);
        if (ctrl.defaultBehaviorLimitations) detailRows.push([l.defaultBehavior, ctrl.defaultBehaviorLimitations]);
        if (ctrl.automation) detailRows.push([l.automation, ctrl.automation]);
        detailRows.push([l.confidence, `${Math.round(ctrl.confidenceScore * 100)}%`]);
        detailRows.push([l.reviewStatus, ctrl.reviewStatus]);
        if (ctrl.frameworkMappings.length > 0) {
          detailRows.push([l.frameworkMappings, ctrl.frameworkMappings.join(', ')]);
        }
        if (detailRows.length > 0) {
          autoTable(doc, {
            startY: y, head: [], body: detailRows, theme: 'plain',
            styles: { fontSize: 8, cellPadding: 2, overflow: 'linebreak' },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 45, textColor: GRAY as any }, 1: { cellWidth: contentW - 45 } },
            margin: { left: margin, right: margin },
          });
          y = (doc as any).lastAutoTable.finalY + 3;
        }

        if (ctrl.threatScenarios.length > 0) {
          checkPageBreak(20);
          doc.setFontSize(8);
          doc.setTextColor(...PRIMARY);
          doc.text(l.threatModeling, margin + 2, y + 3);
          y += 6;
          autoTable(doc, {
            startY: y,
            head: [[l.threatName, l.strideCategory, l.likelihood, l.impact]],
            body: ctrl.threatScenarios.map(ts => [ts.threatName, ts.strideCategory.replace(/_/g, ' '), ts.likelihood.replace(/_/g, ' '), ts.impact]),
            theme: 'striped', styles: { fontSize: 7, cellPadding: 2 },
            headStyles: { fillColor: PRIMARY as any, textColor: [255, 255, 255] },
            margin: { left: margin, right: margin },
          });
          y = (doc as any).lastAutoTable.finalY + 3;
        }

        if (ctrl.sourceTraceability.length > 0) {
          checkPageBreak(15);
          doc.setFontSize(8);
          doc.setTextColor(...PRIMARY);
          doc.text(l.sourceTraceability, margin + 2, y + 3);
          y += 6;
          autoTable(doc, {
            startY: y,
            head: [[l.sourceName, l.excerpt, l.sourceConfidence]],
            body: ctrl.sourceTraceability.map(s => [s.sourceName, s.excerpt.length > 100 ? s.excerpt.substring(0, 100) + '...' : s.excerpt, `${Math.round(s.confidence * 100)}%`]),
            theme: 'striped', styles: { fontSize: 7, cellPadding: 2, overflow: 'linebreak' },
            headStyles: { fillColor: GRAY as any, textColor: [255, 255, 255] },
            columnStyles: { 1: { cellWidth: contentW - 70 } },
            margin: { left: margin, right: margin },
          });
          y = (doc as any).lastAutoTable.finalY + 3;
        }

        y += 5;
        addFooter(doc.getNumberOfPages());
      });
    });
  }

  // ─── 4. ANNEX A — FRAMEWORK COVERAGE ───
  if (sec.annexA) {
    addNewPage();
    sn++;
    doc.setFontSize(18);
    doc.setTextColor(...PRIMARY);
    doc.text(`${sn}. ${l.annexA}`, margin, y);
    y += 12;
    const fwCoverage = getFrameworkCoverage(opts.controls);
    autoTable(doc, {
      startY: y,
      head: [[l.framework, l.controlCount, l.coveragePercent]],
      body: fwCoverage.map(fw => [fw.framework, `${fw.count}`, `${fw.percent}%`]),
      theme: 'striped', styles: { fontSize: 9, cellPadding: 4 },
      headStyles: { fillColor: PRIMARY as any, textColor: [255, 255, 255] },
      margin: { left: margin, right: margin },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
    addFooter(doc.getNumberOfPages());
  }

  // ─── 5. ANNEX B — SOURCE TRACEABILITY INDEX ───
  if (sec.annexB) {
    addNewPage();
    sn++;
    doc.setFontSize(18);
    doc.setTextColor(...PRIMARY);
    doc.text(`${sn}. ${l.annexB}`, margin, y);
    y += 12;
    const srcIndex = getSourceIndex(opts.controls);
    autoTable(doc, {
      startY: y,
      head: [[l.sourceName, l.controlCount, l.sourceConfidence]],
      body: srcIndex.map(s => [s.name, `${s.controlIds.length}`, `${s.avgConf}%`]),
      theme: 'striped', styles: { fontSize: 9, cellPadding: 4 },
      headStyles: { fillColor: PRIMARY as any, textColor: [255, 255, 255] },
      margin: { left: margin, right: margin },
    });
    addFooter(doc.getNumberOfPages());
  }

  // Handle case where no cover was first page (remove blank first page)
  if (!sec.cover && doc.getNumberOfPages() > 1) {
    // First page is blank, already handled by addNewPage logic
  }

  // Save
  const filename = `baseline-${opts.projectName.replace(/\s+/g, '-').toLowerCase()}-v${opts.version}.pdf`;
  doc.save(filename);
}

export function generateBaselineDOCX(opts: DocumentOptions): void {
  const l = labels[opts.locale] || labels.en;
  const grouped = groupByCategory(opts.controls);
  const fwCoverage = getFrameworkCoverage(opts.controls);
  const srcIndex = getSourceIndex(opts.controls);
  const dateStr = opts.publishedAt
    ? new Date(opts.publishedAt).toLocaleDateString(opts.locale === 'pt' ? 'pt-BR' : opts.locale === 'es' ? 'es-ES' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString();

  // Generate HTML-based DOCX
  let html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
  <head><meta charset="utf-8"><style>
    body { font-family: Calibri, Arial, sans-serif; color: #1a1a2e; margin: 40px; line-height: 1.6; }
    h1 { color: #6d28d9; font-size: 24px; border-bottom: 2px solid #6d28d9; padding-bottom: 6px; margin-top: 30px; }
    h2 { color: #6d28d9; font-size: 18px; margin-top: 24px; }
    h3 { color: #1a1a2e; font-size: 14px; margin-top: 16px; }
    table { border-collapse: collapse; width: 100%; margin: 10px 0; }
    th { background: #6d28d9; color: white; padding: 8px 10px; text-align: left; font-size: 11px; }
    td { border: 1px solid #e2e8f0; padding: 6px 10px; font-size: 11px; }
    .cover { text-align: center; padding: 80px 0; page-break-after: always; }
    .cover h1 { font-size: 32px; border: none; color: #6d28d9; }
    .cover .subtitle { font-size: 18px; color: #64748b; margin-top: 10px; }
    .cover .date { font-size: 12px; color: #94a3b8; margin-top: 20px; }
    .stat-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 16px 0; display: flex; justify-content: space-around; }
    .stat-item { text-align: center; }
    .stat-value { font-size: 22px; font-weight: bold; color: #6d28d9; }
    .stat-label { font-size: 10px; color: #64748b; text-transform: uppercase; }
    .control-header { background: #f5f3ff; padding: 8px 12px; border-radius: 4px; margin-top: 14px; }
    .control-id { font-family: monospace; color: #6d28d9; font-size: 11px; }
    .control-title { font-weight: bold; font-size: 13px; }
    .crit-badge { font-size: 10px; font-weight: bold; float: right; }
    .crit-critical { color: #dc2626; }
    .crit-high { color: #ea580c; }
    .crit-medium { color: #ca8a04; }
    .crit-low { color: #16a34a; }
    .section-label { font-size: 10px; color: #6d28d9; font-weight: bold; margin-top: 8px; }
    .toc { page-break-after: always; }
    .page-break { page-break-before: always; }
    .footer { font-size: 8px; color: #94a3b8; text-align: center; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 8px; }
  </style></head><body>`;

  // Cover
  html += `<div class="cover">
    <h1>${l.title}</h1>
    <div class="subtitle">${opts.projectName}</div>
    <div class="subtitle" style="font-size:14px">${opts.technology} — v${opts.version}</div>
    <div class="date">${dateStr}</div>
    <div class="date" style="margin-top:40px">${l.confidential}</div>
  </div>`;

  // TOC
  html += `<div class="toc"><h1>${l.toc}</h1><ol>
    <li>${l.executiveSummary}</li>
    <li>${l.projectOverview}</li>
    <li>${l.securityControls}<ol>`;
  grouped.forEach(g => {
    html += `<li>${getCategoryLabel(g.category, opts.locale)} (${g.controls.length})</li>`;
  });
  html += `</ol></li>
    <li>${l.annexA}</li>
    <li>${l.annexB}</li>
  </ol></div>`;

  // 1. Executive Summary
  html += `<div class="page-break"><h1>1. ${l.executiveSummary}</h1>
    <p>${l.executiveSummaryBody(opts)}</p>
    <div class="stat-box">
      <div class="stat-item"><div class="stat-value">${opts.controls.length}</div><div class="stat-label">${l.totalControls}</div></div>
      <div class="stat-item"><div class="stat-value">${opts.controls.filter(c => c.criticality === 'critical').length}</div><div class="stat-label">Critical</div></div>
      <div class="stat-item"><div class="stat-value">${Math.round(opts.controls.reduce((s, c) => s + c.confidenceScore, 0) / (opts.controls.length || 1) * 100)}%</div><div class="stat-label">${l.confidence}</div></div>
    </div>
  </div>`;

  // 2. Project Overview
  html += `<h1>2. ${l.projectOverview}</h1>
    <table>
      <tr><td style="font-weight:bold;background:#f8fafc;width:180px">${l.projectName}</td><td>${opts.projectName}</td></tr>
      <tr><td style="font-weight:bold;background:#f8fafc">${l.technology}</td><td>${opts.technology}</td></tr>
      <tr><td style="font-weight:bold;background:#f8fafc">${l.version}</td><td>v${opts.version}</td></tr>
      <tr><td style="font-weight:bold;background:#f8fafc">${l.totalControls}</td><td>${opts.controls.length}</td></tr>
      <tr><td style="font-weight:bold;background:#f8fafc">${l.publishedDate}</td><td>${dateStr}</td></tr>
    </table>`;

  // 3. Security Controls
  html += `<div class="page-break"><h1>3. ${l.securityControls}</h1>`;
  grouped.forEach((group, gi) => {
    html += `<h2>3.${gi + 1}. ${getCategoryLabel(group.category, opts.locale)}</h2>`;

    group.controls.forEach(ctrl => {
      html += `<div class="control-header">
        <span class="control-id">${ctrl.controlId}</span> &nbsp;
        <span class="control-title">${ctrl.title}</span>
        <span class="crit-badge crit-${ctrl.criticality}">${ctrl.criticality.toUpperCase()}</span>
      </div>`;

      html += `<table>`;
      if (ctrl.description) html += `<tr><td style="font-weight:bold;width:160px">${l.description}</td><td>${ctrl.description}</td></tr>`;
      if (ctrl.applicability) html += `<tr><td style="font-weight:bold">${l.applicability}</td><td>${ctrl.applicability}</td></tr>`;
      if (ctrl.securityRisk) html += `<tr><td style="font-weight:bold">${l.securityRisk}</td><td>${ctrl.securityRisk}</td></tr>`;
      if (ctrl.defaultBehaviorLimitations) html += `<tr><td style="font-weight:bold">${l.defaultBehavior}</td><td>${ctrl.defaultBehaviorLimitations}</td></tr>`;
      if (ctrl.automation) html += `<tr><td style="font-weight:bold">${l.automation}</td><td>${ctrl.automation}</td></tr>`;
      html += `<tr><td style="font-weight:bold">${l.confidence}</td><td>${Math.round(ctrl.confidenceScore * 100)}%</td></tr>`;
      html += `<tr><td style="font-weight:bold">${l.reviewStatus}</td><td>${ctrl.reviewStatus}</td></tr>`;
      if (ctrl.frameworkMappings.length > 0) {
        html += `<tr><td style="font-weight:bold">${l.frameworkMappings}</td><td>${ctrl.frameworkMappings.join(', ')}</td></tr>`;
      }
      html += `</table>`;

      // Threats
      if (ctrl.threatScenarios.length > 0) {
        html += `<div class="section-label">${l.threatModeling}</div>
          <table><tr><th>${l.threatName}</th><th>${l.strideCategory}</th><th>${l.likelihood}</th><th>${l.impact}</th></tr>`;
        ctrl.threatScenarios.forEach(ts => {
          html += `<tr><td>${ts.threatName}</td><td>${ts.strideCategory.replace(/_/g, ' ')}</td><td>${ts.likelihood.replace(/_/g, ' ')}</td><td>${ts.impact}</td></tr>`;
        });
        html += `</table>`;
      }

      // Sources
      if (ctrl.sourceTraceability.length > 0) {
        html += `<div class="section-label">${l.sourceTraceability}</div>
          <table><tr><th>${l.sourceName}</th><th>${l.excerpt}</th><th>${l.sourceConfidence}</th></tr>`;
        ctrl.sourceTraceability.forEach(s => {
          html += `<tr><td>${s.sourceName}</td><td style="font-style:italic">${s.excerpt.length > 120 ? s.excerpt.substring(0, 120) + '...' : s.excerpt}</td><td>${Math.round(s.confidence * 100)}%</td></tr>`;
        });
        html += `</table>`;
      }
    });
  });
  html += `</div>`;

  // 4. Annex A
  html += `<div class="page-break"><h1>4. ${l.annexA}</h1>
    <table><tr><th>${l.framework}</th><th>${l.controlCount}</th><th>${l.coveragePercent}</th></tr>`;
  fwCoverage.forEach(fw => {
    html += `<tr><td>${fw.framework}</td><td>${fw.count}</td><td>${fw.percent}%</td></tr>`;
  });
  html += `</table></div>`;

  // 5. Annex B
  html += `<h1>5. ${l.annexB}</h1>
    <table><tr><th>${l.sourceName}</th><th>${l.controlCount}</th><th>${l.sourceConfidence}</th></tr>`;
  srcIndex.forEach(s => {
    html += `<tr><td>${s.name}</td><td>${s.controlIds.length}</td><td>${s.avgConf}%</td></tr>`;
  });
  html += `</table>`;

  html += `<div class="footer">${l.generatedBy} — ${dateStr}</div></body></html>`;

  // Download as .doc (Word-compatible HTML)
  const blob = new Blob(['\ufeff' + html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `baseline-${opts.projectName.replace(/\s+/g, '-').toLowerCase()}-v${opts.version}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
