import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ControlItem } from '@/types';
import { AUREUM_LOGO_BASE64 } from '@/assets/aureumLogoBase64';

export interface DocumentSections {
  cover: boolean;
  toc: boolean;
  executiveSummary: boolean;
  projectOverview: boolean;
  securityControls: boolean;
  annexA: boolean;
  annexB: boolean;
}

export const DEFAULT_SECTIONS: DocumentSections = {
  cover: true,
  toc: true,
  executiveSummary: true,
  projectOverview: true,
  securityControls: true,
  annexA: true,
  annexB: true,
};

interface DocumentOptions {
  projectName: string;
  technology: string;
  version: number;
  publishedAt?: string;
  locale: 'en' | 'pt' | 'es';
  controls: ControlItem[];
  sources?: any[];
  sections?: DocumentSections;
  watermark?: boolean;
}

const CATEGORY_LABELS: Record<string, Record<string, string>> = {
  identity: { en: 'Identity & Access', pt: 'Identidade e Acesso', es: 'Identidad y Acceso' },
  encryption: { en: 'Encryption & Data Protection', pt: 'Criptografia e Proteção de Dados', es: 'Cifrado y Protección de Datos' },
  logging: { en: 'Logging & Monitoring', pt: 'Logs e Monitoramento', es: 'Logs y Monitoreo' },
  network: { en: 'Network Security', pt: 'Segurança de Rede', es: 'Seguridad de Red' },
  storage: { en: 'Storage & Resilience', pt: 'Armazenamento e Resiliência', es: 'Almacenamiento y Resiliencia' },
  runtime: { en: 'Runtime Security', pt: 'Segurança em Tempo de Execução', es: 'Seguridad en Tiempo de Ejecución' },
  cicd: { en: 'CI/CD & Supply Chain', pt: 'CI/CD e Cadeia de Suprimentos', es: 'CI/CD y Cadena de Suministro' },
};

const CATEGORY_ORDER = ['identity', 'encryption', 'network', 'logging', 'storage', 'runtime', 'cicd'];

const labels = {
  en: {
    title: 'Security Baseline Document',
    toc: 'Table of Contents',
    executiveSummary: 'Executive Summary',
    executiveSummaryBody: (opts: DocumentOptions) =>
      `This document presents the security baseline for ${opts.technology}, version ${opts.version}. It contains ${opts.controls.length} security controls organized by category, with framework mappings, threat modeling, and source traceability. The baseline was generated and reviewed using Aureum Security Baseline Suite.`,
    projectOverview: 'Project Overview',
    projectName: 'Project Name',
    technology: 'Technology',
    version: 'Version',
    totalControls: 'Total Controls',
    publishedDate: 'Published Date',
    securityControls: 'Security Controls',
    controlId: 'Control ID',
    description: 'Description',
    applicability: 'Applicability',
    securityRisk: 'Security Risk',
    defaultBehavior: 'Default Behavior / Limitations',
    automation: 'Automation / Guardrail',
    criticality: 'Criticality',
    confidence: 'Confidence Score',
    reviewStatus: 'Review Status',
    frameworkMappings: 'Framework Mappings',
    threatModeling: 'Threat Modeling',
    threatName: 'Threat',
    strideCategory: 'STRIDE Category',
    attackVector: 'Attack Vector',
    likelihood: 'Likelihood',
    impact: 'Impact',
    mitigations: 'Mitigations',
    sourceTraceability: 'Source Traceability',
    sourceName: 'Source',
    excerpt: 'Excerpt',
    sourceConfidence: 'Confidence',
    annexA: 'Annex A — Framework Coverage Summary',
    annexB: 'Annex B — Source Traceability Index',
    framework: 'Framework',
    controlCount: 'Controls Mapped',
    coveragePercent: 'Coverage %',
    generatedBy: 'Generated by Aureum Security Baseline Suite',
    confidential: 'CONFIDENTIAL',
    page: 'Page',
    noCategory: 'Other',
  },
  pt: {
    title: 'Documento de Baseline de Segurança',
    toc: 'Sumário',
    executiveSummary: 'Resumo Executivo',
    executiveSummaryBody: (opts: DocumentOptions) =>
      `Este documento apresenta o baseline de segurança para ${opts.technology}, versão ${opts.version}. Contém ${opts.controls.length} controles de segurança organizados por categoria, com mapeamentos de frameworks, modelagem de ameaças e rastreabilidade de fontes. O baseline foi gerado e revisado usando o Aureum Security Baseline Suite.`,
    projectOverview: 'Visão Geral do Projeto',
    projectName: 'Nome do Projeto',
    technology: 'Tecnologia',
    version: 'Versão',
    totalControls: 'Total de Controles',
    publishedDate: 'Data de Publicação',
    securityControls: 'Controles de Segurança',
    controlId: 'ID do Controle',
    description: 'Descrição',
    applicability: 'Aplicabilidade',
    securityRisk: 'Risco de Segurança',
    defaultBehavior: 'Comportamento Padrão / Limitações',
    automation: 'Automação / Guardrail',
    criticality: 'Criticidade',
    confidence: 'Score de Confiança',
    reviewStatus: 'Status de Revisão',
    frameworkMappings: 'Mapeamentos de Frameworks',
    threatModeling: 'Modelagem de Ameaças',
    threatName: 'Ameaça',
    strideCategory: 'Categoria STRIDE',
    attackVector: 'Vetor de Ataque',
    likelihood: 'Probabilidade',
    impact: 'Impacto',
    mitigations: 'Mitigações',
    sourceTraceability: 'Rastreabilidade de Fontes',
    sourceName: 'Fonte',
    excerpt: 'Trecho',
    sourceConfidence: 'Confiança',
    annexA: 'Anexo A — Resumo de Cobertura de Frameworks',
    annexB: 'Anexo B — Índice de Rastreabilidade de Fontes',
    framework: 'Framework',
    controlCount: 'Controles Mapeados',
    coveragePercent: 'Cobertura %',
    generatedBy: 'Gerado pelo Aureum Security Baseline Suite',
    confidential: 'CONFIDENCIAL',
    page: 'Página',
    noCategory: 'Outros',
  },
  es: {
    title: 'Documento de Baseline de Seguridad',
    toc: 'Índice',
    executiveSummary: 'Resumen Ejecutivo',
    executiveSummaryBody: (opts: DocumentOptions) =>
      `Este documento presenta el baseline de seguridad para ${opts.technology}, versión ${opts.version}. Contiene ${opts.controls.length} controles de seguridad organizados por categoría, con mapeos de frameworks, modelado de amenazas y trazabilidad de fuentes. El baseline fue generado y revisado usando Aureum Security Baseline Suite.`,
    projectOverview: 'Visión General del Proyecto',
    projectName: 'Nombre del Proyecto',
    technology: 'Tecnología',
    version: 'Versión',
    totalControls: 'Total de Controles',
    publishedDate: 'Fecha de Publicación',
    securityControls: 'Controles de Seguridad',
    controlId: 'ID del Control',
    description: 'Descripción',
    applicability: 'Aplicabilidad',
    securityRisk: 'Riesgo de Seguridad',
    defaultBehavior: 'Comportamiento Predeterminado / Limitaciones',
    automation: 'Automatización / Guardrail',
    criticality: 'Criticidad',
    confidence: 'Score de Confianza',
    reviewStatus: 'Estado de Revisión',
    frameworkMappings: 'Mapeos de Frameworks',
    threatModeling: 'Modelado de Amenazas',
    threatName: 'Amenaza',
    strideCategory: 'Categoría STRIDE',
    attackVector: 'Vector de Ataque',
    likelihood: 'Probabilidad',
    impact: 'Impacto',
    mitigations: 'Mitigaciones',
    sourceTraceability: 'Trazabilidad de Fuentes',
    sourceName: 'Fuente',
    excerpt: 'Extracto',
    sourceConfidence: 'Confianza',
    annexA: 'Anexo A — Resumen de Cobertura de Frameworks',
    annexB: 'Anexo B — Índice de Trazabilidad de Fuentes',
    framework: 'Framework',
    controlCount: 'Controles Mapeados',
    coveragePercent: 'Cobertura %',
    generatedBy: 'Generado por Aureum Security Baseline Suite',
    confidential: 'CONFIDENCIAL',
    page: 'Página',
    noCategory: 'Otros',
  },
};

function getCategoryLabel(cat: string, locale: string): string {
  return CATEGORY_LABELS[cat]?.[locale] || cat.charAt(0).toUpperCase() + cat.slice(1);
}

function groupByCategory(controls: ControlItem[]): { category: string; controls: ControlItem[] }[] {
  const groups: Record<string, ControlItem[]> = {};
  for (const c of controls) {
    const cat = c.category || 'other';
    if (!groups[cat]) groups[cat] = [];
    groups[cat].push(c);
  }
  return CATEGORY_ORDER
    .filter(cat => groups[cat]?.length)
    .map(cat => ({ category: cat, controls: groups[cat] }))
    .concat(
      Object.keys(groups)
        .filter(cat => !CATEGORY_ORDER.includes(cat))
        .map(cat => ({ category: cat, controls: groups[cat] }))
    );
}

function getFrameworkCoverage(controls: ControlItem[]) {
  const fwMap: Record<string, number> = {};
  for (const c of controls) {
    for (const m of c.frameworkMappings) {
      const prefix = m.split(' ')[0].split('-')[0];
      fwMap[prefix] = (fwMap[prefix] || 0) + 1;
    }
  }
  return Object.entries(fwMap).map(([fw, count]) => ({
    framework: fw,
    count,
    percent: Math.round((count / controls.length) * 100),
  }));
}

function getSourceIndex(controls: ControlItem[]) {
  const srcMap: Record<string, { name: string; controlIds: string[]; avgConf: number; total: number }> = {};
  for (const c of controls) {
    for (const s of c.sourceTraceability) {
      if (!srcMap[s.sourceName]) {
        srcMap[s.sourceName] = { name: s.sourceName, controlIds: [], avgConf: 0, total: 0 };
      }
      srcMap[s.sourceName].controlIds.push(c.controlId);
      srcMap[s.sourceName].avgConf += s.confidence;
      srcMap[s.sourceName].total += 1;
    }
  }
  return Object.values(srcMap).map(s => ({
    ...s,
    avgConf: s.total > 0 ? Math.round((s.avgConf / s.total) * 100) : 0,
  }));
}

/* ═══════════════════════════════════════════════════════
   PDF GENERATION — Premium Aureum Brand
   ═══════════════════════════════════════════════════════ */

export function generateBaselinePDF(opts: DocumentOptions): void {
  const l = labels[opts.locale] || labels.en;
  const sec = opts.sections || DEFAULT_SECTIONS;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 0;

  // ── Aureum Brand Palette ──
  const GOLD: [number, number, number] = [191, 155, 81];       // #BF9B51 champagne gold
  const GOLD_LIGHT: [number, number, number] = [230, 213, 173]; // #E6D5AD warm gold tint
  const OBSIDIAN: [number, number, number] = [22, 25, 37];      // #161925 deep obsidian
  const GRAPHITE: [number, number, number] = [55, 60, 75];      // #373C4B graphite
  const SLATE: [number, number, number] = [120, 125, 140];      // #787D8C muted slate
  const IVORY: [number, number, number] = [250, 248, 243];      // #FAF8F3 warm ivory
  const CREAM: [number, number, number] = [245, 241, 233];      // #F5F1E9 cream

  const addFooter = (pageNum: number) => {
    // Thin gold line
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.3);
    doc.line(margin, pageH - 14, pageW - margin, pageH - 14);
    doc.setFontSize(7);
    doc.setTextColor(...SLATE);
    doc.text(l.confidential, margin, pageH - 8);
    doc.text(`${l.page} ${pageNum}`, pageW - margin, pageH - 8, { align: 'right' });
    doc.setTextColor(...GOLD);
    doc.text(l.generatedBy, pageW / 2, pageH - 8, { align: 'center' });
  };

  const addWatermark = () => {
    const wmSize = 82;
    const wmX = (pageW - wmSize) / 2;
    const wmY = (pageH - wmSize) / 2;

    try {
      const GState = (doc as any).GState;
      if (GState) {
        (doc as any).setGState(new GState({ opacity: 0.04 }));
      }

      doc.addImage(AUREUM_LOGO_BASE64, 'PNG', wmX, wmY, wmSize, wmSize);

      if (GState) {
        (doc as any).setGState(new GState({ opacity: 1 }));
      }
    } catch {
      // Watermark is decorative; ignore rendering failures.
    }
  };

  const addPageHeader = (title: string) => {
    if (opts.watermark !== false) addWatermark();
    // Subtle gold accent bar at top
    doc.setFillColor(...GOLD);
    doc.rect(0, 0, pageW, 2, 'F');
    // Header area
    doc.setFillColor(...IVORY);
    doc.rect(0, 2, pageW, 14, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...GOLD);
    doc.text('AUREUM SECURITY BASELINE SUITE', margin, 10);
    doc.setTextColor(...SLATE);
    doc.text(title, pageW - margin, 10, { align: 'right' });
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageH - 20) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
      addPageHeader(opts.projectName);
      y = 24;
    }
  };

  const dateStr = opts.publishedAt
    ? new Date(opts.publishedAt).toLocaleDateString(opts.locale === 'pt' ? 'pt-BR' : opts.locale === 'es' ? 'es-ES' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString();
  const grouped = groupByCategory(opts.controls);
  let isFirstPage = true;

  const addNewPage = () => {
    if (!isFirstPage) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
    } else {
      isFirstPage = false;
    }
    addPageHeader(opts.projectName);
    y = 24;
  };

  // ─── COVER PAGE ───
  if (sec.cover) {
    // Full obsidian background
    doc.setFillColor(...OBSIDIAN);
    doc.rect(0, 0, pageW, pageH, 'F');

    // Gold decorative line at top
    doc.setFillColor(...GOLD);
    doc.rect(0, 0, pageW, 3, 'F');

    // Logo
    try {
      doc.addImage(AUREUM_LOGO_BASE64, 'PNG', pageW / 2 - 18, 45, 36, 36);
    } catch { /* logo optional */ }

    // Brand name
    doc.setFontSize(11);
    doc.setTextColor(...GOLD);
    doc.text('A U R E U M', pageW / 2, 92, { align: 'center' });
    doc.setFontSize(8);
    doc.setTextColor(...SLATE);
    doc.text('B A S E L I N E   S T U D I O', pageW / 2, 99, { align: 'center' });

    // Decorative gold separator
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.5);
    doc.line(pageW / 2 - 40, 110, pageW / 2 + 40, 110);
    doc.setLineWidth(0.2);
    doc.line(pageW / 2 - 30, 113, pageW / 2 + 30, 113);

    // Title
    doc.setFontSize(26);
    doc.setTextColor(255, 255, 255);
    doc.text(l.title, pageW / 2, 132, { align: 'center' });

    // Project name
    doc.setFontSize(16);
    doc.setTextColor(...GOLD_LIGHT);
    doc.text(opts.projectName, pageW / 2, 148, { align: 'center' });

    // Technology & version
    doc.setFontSize(12);
    doc.setTextColor(...SLATE);
    doc.text(`${opts.technology}  ·  v${opts.version}`, pageW / 2, 162, { align: 'center' });

    // Date
    doc.setFontSize(10);
    doc.setTextColor(160, 160, 175);
    doc.text(dateStr, pageW / 2, 178, { align: 'center' });

    // Bottom gold line + confidential
    doc.setFillColor(...GOLD);
    doc.rect(0, pageH - 18, pageW, 0.5, 'F');
    doc.setFontSize(8);
    doc.setTextColor(...GOLD);
    doc.text(l.confidential, pageW / 2, pageH - 10, { align: 'center' });

    isFirstPage = false;
  }

  // ─── TABLE OF CONTENTS ───
  if (sec.toc) {
    addNewPage();
    doc.setFontSize(20);
    doc.setTextColor(...OBSIDIAN);
    doc.text(l.toc, margin, y + 6);
    // Gold underline
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.8);
    doc.line(margin, y + 10, margin + 50, y + 10);
    y += 20;

    let sectionNum = 0;
    const tocItems: { text: string; indent: boolean }[] = [];
    if (sec.executiveSummary) { sectionNum++; tocItems.push({ text: `${sectionNum}. ${l.executiveSummary}`, indent: false }); }
    if (sec.projectOverview) { sectionNum++; tocItems.push({ text: `${sectionNum}. ${l.projectOverview}`, indent: false }); }
    if (sec.securityControls) {
      sectionNum++;
      tocItems.push({ text: `${sectionNum}. ${l.securityControls}`, indent: false });
      grouped.forEach((g, i) => {
        tocItems.push({ text: `${sectionNum}.${i + 1}  ${getCategoryLabel(g.category, opts.locale)} (${g.controls.length})`, indent: true });
      });
    }
    if (sec.annexA) { sectionNum++; tocItems.push({ text: `${sectionNum}. ${l.annexA}`, indent: false }); }
    if (sec.annexB) { sectionNum++; tocItems.push({ text: `${sectionNum}. ${l.annexB}`, indent: false }); }

    doc.setFontSize(10);
    for (const item of tocItems) {
      if (item.indent) {
        doc.setTextColor(...SLATE);
        doc.text(item.text, margin + 10, y);
      } else {
        doc.setTextColor(...OBSIDIAN);
        doc.setFont(undefined!, 'bold');
        doc.text(item.text, margin, y);
        doc.setFont(undefined!, 'normal');
      }
      y += 7;
    }
    addFooter(doc.getNumberOfPages());
  }

  // ─── SECTIONS ───
  let sn = 0;

  const drawSectionTitle = (title: string) => {
    doc.setFontSize(18);
    doc.setTextColor(...OBSIDIAN);
    doc.text(title, margin, y + 4);
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.6);
    doc.line(margin, y + 8, margin + 55, y + 8);
    y += 16;
  };

  // ─── EXECUTIVE SUMMARY ───
  if (sec.executiveSummary) {
    addNewPage();
    sn++;
    drawSectionTitle(`${sn}. ${l.executiveSummary}`);

    doc.setFontSize(10);
    doc.setTextColor(...GRAPHITE);
    const summaryLines = doc.splitTextToSize(l.executiveSummaryBody(opts), contentW);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 5 + 10;

    // Stats boxes with gold accent
    const stats = [
      { label: l.totalControls, value: `${opts.controls.length}` },
      { label: l.criticality, value: `${opts.controls.filter(c => c.criticality === 'critical').length} critical` },
      { label: l.confidence, value: `${Math.round(opts.controls.reduce((s, c) => s + c.confidenceScore, 0) / (opts.controls.length || 1) * 100)}%` },
    ];
    doc.setFillColor(...CREAM);
    doc.roundedRect(margin, y, contentW, 24, 2, 2, 'F');
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.4);
    doc.roundedRect(margin, y, contentW, 24, 2, 2, 'S');

    const statW = contentW / stats.length;
    stats.forEach((stat, i) => {
      const sx = margin + statW * i + statW / 2;
      // Vertical divider (except first)
      if (i > 0) {
        doc.setDrawColor(...GOLD_LIGHT);
        doc.setLineWidth(0.2);
        doc.line(margin + statW * i, y + 4, margin + statW * i, y + 20);
      }
      doc.setFontSize(15);
      doc.setTextColor(...GOLD);
      doc.text(stat.value, sx, y + 11, { align: 'center' });
      doc.setFontSize(7);
      doc.setTextColor(...SLATE);
      doc.text(stat.label.toUpperCase(), sx, y + 18, { align: 'center' });
    });
    y += 32;
    addFooter(doc.getNumberOfPages());
  }

  // ─── PROJECT OVERVIEW ───
  if (sec.projectOverview) {
    addNewPage();
    sn++;
    drawSectionTitle(`${sn}. ${l.projectOverview}`);

    autoTable(doc, {
      startY: y,
      head: [],
      body: [
        [l.projectName, opts.projectName],
        [l.technology, opts.technology],
        [l.version, `v${opts.version}`],
        [l.totalControls, `${opts.controls.length}`],
        [l.publishedDate, dateStr],
      ],
      theme: 'plain',
      styles: { fontSize: 9, cellPadding: 5, lineColor: GOLD_LIGHT as any, lineWidth: 0.2 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 55, fillColor: CREAM as any, textColor: OBSIDIAN as any },
        1: { cellWidth: contentW - 55, textColor: GRAPHITE as any },
      },
      margin: { left: margin, right: margin },
      didDrawCell: (data: any) => {
        if (data.column.index === 0) {
          // Left gold accent bar
          doc.setFillColor(...GOLD);
          doc.rect(data.cell.x, data.cell.y, 1, data.cell.height, 'F');
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
    addFooter(doc.getNumberOfPages());
  }

  // ─── SECURITY CONTROLS ───
  if (sec.securityControls) {
    addNewPage();
    sn++;
    drawSectionTitle(`${sn}. ${l.securityControls}`);

    grouped.forEach((group, gi) => {
      checkPageBreak(30);
      // Category subheader with gold bullet
      doc.setFillColor(...GOLD);
      doc.circle(margin + 2, y - 1, 1.5, 'F');
      doc.setFontSize(13);
      doc.setTextColor(...OBSIDIAN);
      doc.text(`${sn}.${gi + 1}. ${getCategoryLabel(group.category, opts.locale)}`, margin + 7, y);
      y += 9;

      group.controls.forEach((ctrl) => {
        checkPageBreak(60);
        // Control header bar with gold left border
        doc.setFillColor(...CREAM);
        doc.roundedRect(margin, y, contentW, 8, 1, 1, 'F');
        doc.setFillColor(...GOLD);
        doc.rect(margin, y, 1.5, 8, 'F');

        doc.setFontSize(8);
        doc.setTextColor(...GOLD);
        doc.text(ctrl.controlId, margin + 5, y + 5.5);
        doc.setTextColor(...OBSIDIAN);
        doc.setFont(undefined!, 'bold');
        doc.text(ctrl.title, margin + 32, y + 5.5);
        doc.setFont(undefined!, 'normal');
        const critColors: Record<string, [number, number, number]> = {
          critical: [200, 40, 40], high: [210, 100, 20], medium: [180, 140, 20], low: [40, 140, 70],
        };
        const cc = critColors[ctrl.criticality] || SLATE;
        doc.setTextColor(...cc);
        doc.setFontSize(7);
        doc.text(ctrl.criticality.toUpperCase(), pageW - margin - 3, y + 5.5, { align: 'right' });
        y += 12;

        const detailRows: string[][] = [];
        if (ctrl.description) detailRows.push([l.description, ctrl.description]);
        if (ctrl.applicability) detailRows.push([l.applicability, ctrl.applicability]);
        if (ctrl.securityRisk) detailRows.push([l.securityRisk, ctrl.securityRisk]);
        if (ctrl.defaultBehaviorLimitations) detailRows.push([l.defaultBehavior, ctrl.defaultBehaviorLimitations]);
        if (ctrl.automation) detailRows.push([l.automation, ctrl.automation]);
        detailRows.push([l.confidence, `${Math.round(ctrl.confidenceScore * 100)}%`]);
        detailRows.push([l.reviewStatus, ctrl.reviewStatus]);
        if (ctrl.frameworkMappings.length > 0) {
          detailRows.push([l.frameworkMappings, ctrl.frameworkMappings.join(', ')]);
        }
        if (detailRows.length > 0) {
          autoTable(doc, {
            startY: y, head: [], body: detailRows, theme: 'plain',
            styles: { fontSize: 8, cellPadding: 2.5, overflow: 'linebreak', lineColor: [230, 228, 220] as any, lineWidth: 0.1 },
            columnStyles: {
              0: { fontStyle: 'bold', cellWidth: 45, textColor: SLATE as any },
              1: { cellWidth: contentW - 45, textColor: GRAPHITE as any },
            },
            margin: { left: margin, right: margin },
          });
          y = (doc as any).lastAutoTable.finalY + 3;
        }

        if (ctrl.threatScenarios.length > 0) {
          checkPageBreak(20);
          doc.setFontSize(8);
          doc.setTextColor(...GOLD);
          doc.text(l.threatModeling, margin + 2, y + 3);
          y += 6;
          autoTable(doc, {
            startY: y,
            head: [[l.threatName, l.strideCategory, l.likelihood, l.impact]],
            body: ctrl.threatScenarios.map(ts => [ts.threatName, ts.strideCategory.replace(/_/g, ' '), ts.likelihood.replace(/_/g, ' '), ts.impact]),
            theme: 'striped', styles: { fontSize: 7, cellPadding: 2.5 },
            headStyles: { fillColor: OBSIDIAN as any, textColor: GOLD_LIGHT as any, fontStyle: 'bold' },
            alternateRowStyles: { fillColor: IVORY as any },
            margin: { left: margin, right: margin },
          });
          y = (doc as any).lastAutoTable.finalY + 3;
        }

        if (ctrl.sourceTraceability.length > 0) {
          checkPageBreak(15);
          doc.setFontSize(8);
          doc.setTextColor(...GOLD);
          doc.text(l.sourceTraceability, margin + 2, y + 3);
          y += 6;
          autoTable(doc, {
            startY: y,
            head: [[l.sourceName, l.excerpt, l.sourceConfidence]],
            body: ctrl.sourceTraceability.map(s => [s.sourceName, s.excerpt.length > 100 ? s.excerpt.substring(0, 100) + '...' : s.excerpt, `${Math.round(s.confidence * 100)}%`]),
            theme: 'striped', styles: { fontSize: 7, cellPadding: 2.5, overflow: 'linebreak' },
            headStyles: { fillColor: GRAPHITE as any, textColor: [255, 255, 255] },
            alternateRowStyles: { fillColor: IVORY as any },
            columnStyles: { 1: { cellWidth: contentW - 70 } },
            margin: { left: margin, right: margin },
          });
          y = (doc as any).lastAutoTable.finalY + 3;
        }

        y += 5;
        addFooter(doc.getNumberOfPages());
      });
    });
  }

  // ─── ANNEX A — FRAMEWORK COVERAGE ───
  if (sec.annexA) {
    addNewPage();
    sn++;
    drawSectionTitle(`${sn}. ${l.annexA}`);

    const fwCoverage = getFrameworkCoverage(opts.controls);
    autoTable(doc, {
      startY: y,
      head: [[l.framework, l.controlCount, l.coveragePercent]],
      body: fwCoverage.map(fw => [fw.framework, `${fw.count}`, `${fw.percent}%`]),
      theme: 'striped', styles: { fontSize: 9, cellPadding: 5 },
      headStyles: { fillColor: OBSIDIAN as any, textColor: GOLD_LIGHT as any, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: IVORY as any },
      margin: { left: margin, right: margin },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
    addFooter(doc.getNumberOfPages());
  }

  // ─── ANNEX B — SOURCE TRACEABILITY INDEX ───
  if (sec.annexB) {
    addNewPage();
    sn++;
    drawSectionTitle(`${sn}. ${l.annexB}`);

    const srcIndex = getSourceIndex(opts.controls);
    autoTable(doc, {
      startY: y,
      head: [[l.sourceName, l.controlCount, l.sourceConfidence]],
      body: srcIndex.map(s => [s.name, `${s.controlIds.length}`, `${s.avgConf}%`]),
      theme: 'striped', styles: { fontSize: 9, cellPadding: 5 },
      headStyles: { fillColor: OBSIDIAN as any, textColor: GOLD_LIGHT as any, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: IVORY as any },
      margin: { left: margin, right: margin },
    });
    addFooter(doc.getNumberOfPages());
  }

  const filename = `baseline-${opts.projectName.replace(/\s+/g, '-').toLowerCase()}-v${opts.version}.pdf`;
  doc.save(filename);
}

/* ═══════════════════════════════════════════════════════
   DOCX GENERATION — Premium Aureum Brand
   ═══════════════════════════════════════════════════════ */

export function generateBaselineDOCX(opts: DocumentOptions): void {
  const l = labels[opts.locale] || labels.en;
  const sec = opts.sections || DEFAULT_SECTIONS;
  const grouped = groupByCategory(opts.controls);
  const fwCoverage = getFrameworkCoverage(opts.controls);
  const srcIndex = getSourceIndex(opts.controls);
  const dateStr = opts.publishedAt
    ? new Date(opts.publishedAt).toLocaleDateString(opts.locale === 'pt' ? 'pt-BR' : opts.locale === 'es' ? 'es-ES' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString();

  let html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
  <head><meta charset="utf-8"><style>
    body { font-family: Calibri, Arial, sans-serif; color: #161925; margin: 40px; line-height: 1.6; }
    h1 { color: #161925; font-size: 24px; border-bottom: 2px solid #BF9B51; padding-bottom: 6px; margin-top: 30px; }
    h2 { color: #373C4B; font-size: 18px; margin-top: 24px; }
    h3 { color: #161925; font-size: 14px; margin-top: 16px; }
    table { border-collapse: collapse; width: 100%; margin: 10px 0; }
    th { background: #161925; color: #E6D5AD; padding: 8px 10px; text-align: left; font-size: 11px; }
    td { border: 1px solid #E6D5AD; padding: 6px 10px; font-size: 11px; }
    .cover { text-align: center; padding: 60px 0; page-break-after: always; background: #161925; color: white; }
    .cover h1 { font-size: 28px; border: none; color: white; border-bottom: 2px solid #BF9B51; display: inline-block; padding-bottom: 8px; }
    .cover .brand { font-size: 12px; color: #BF9B51; letter-spacing: 6px; margin-bottom: 10px; }
    .cover .subtitle { font-size: 18px; color: #E6D5AD; margin-top: 10px; }
    .cover .date { font-size: 12px; color: #787D8C; margin-top: 20px; }
    .stat-box { background: #F5F1E9; border: 1px solid #E6D5AD; border-radius: 8px; padding: 16px; margin: 16px 0; display: flex; justify-content: space-around; }
    .stat-item { text-align: center; }
    .stat-value { font-size: 22px; font-weight: bold; color: #BF9B51; }
    .stat-label { font-size: 10px; color: #787D8C; text-transform: uppercase; }
    .control-header { background: #F5F1E9; padding: 8px 12px; border-radius: 4px; margin-top: 14px; border-left: 3px solid #BF9B51; }
    .control-id { font-family: monospace; color: #BF9B51; font-size: 11px; }
    .control-title { font-weight: bold; font-size: 13px; color: #161925; }
    .crit-badge { font-size: 10px; font-weight: bold; float: right; }
    .crit-critical { color: #C82828; }
    .crit-high { color: #D26414; }
    .crit-medium { color: #B48C14; }
    .crit-low { color: #288C46; }
    .section-label { font-size: 10px; color: #BF9B51; font-weight: bold; margin-top: 8px; }
    .toc { page-break-after: always; }
    .page-break { page-break-before: always; }
    .footer { font-size: 8px; color: #787D8C; text-align: center; margin-top: 40px; border-top: 1px solid #E6D5AD; padding-top: 8px; }
  </style></head><body>`;

  let sn = 0;

  if (sec.cover) {
    html += `<div class="cover">
      <div class="brand">A U R E U M</div>
      <p style="font-size:10px;color:#787D8C;letter-spacing:3px">B A S E L I N E &nbsp; S T U D I O</p>
      <hr style="border:none;border-top:1px solid #BF9B51;width:200px;margin:20px auto" />
      <h1>${l.title}</h1>
      <div class="subtitle">${opts.projectName}</div>
      <div class="subtitle" style="font-size:14px;color:#787D8C">${opts.technology} &middot; v${opts.version}</div>
      <div class="date">${dateStr}</div>
      <div class="date" style="margin-top:40px;color:#BF9B51">${l.confidential}</div>
    </div>`;
  }

  if (sec.toc) {
    html += `<div class="toc"><h1>${l.toc}</h1><ol>`;
    if (sec.executiveSummary) html += `<li>${l.executiveSummary}</li>`;
    if (sec.projectOverview) html += `<li>${l.projectOverview}</li>`;
    if (sec.securityControls) {
      html += `<li>${l.securityControls}<ol>`;
      grouped.forEach(g => { html += `<li>${getCategoryLabel(g.category, opts.locale)} (${g.controls.length})</li>`; });
      html += `</ol></li>`;
    }
    if (sec.annexA) html += `<li>${l.annexA}</li>`;
    if (sec.annexB) html += `<li>${l.annexB}</li>`;
    html += `</ol></div>`;
  }

  if (sec.executiveSummary) {
    sn++;
    html += `<div class="page-break"><h1>${sn}. ${l.executiveSummary}</h1>
      <p>${l.executiveSummaryBody(opts)}</p>
      <div class="stat-box">
        <div class="stat-item"><div class="stat-value">${opts.controls.length}</div><div class="stat-label">${l.totalControls}</div></div>
        <div class="stat-item"><div class="stat-value">${opts.controls.filter(c => c.criticality === 'critical').length}</div><div class="stat-label">Critical</div></div>
        <div class="stat-item"><div class="stat-value">${Math.round(opts.controls.reduce((s, c) => s + c.confidenceScore, 0) / (opts.controls.length || 1) * 100)}%</div><div class="stat-label">${l.confidence}</div></div>
      </div>
    </div>`;
  }

  if (sec.projectOverview) {
    sn++;
    html += `<h1>${sn}. ${l.projectOverview}</h1>
      <table>
        <tr><td style="font-weight:bold;background:#F5F1E9;width:180px;border-left:3px solid #BF9B51">${l.projectName}</td><td>${opts.projectName}</td></tr>
        <tr><td style="font-weight:bold;background:#F5F1E9;border-left:3px solid #BF9B51">${l.technology}</td><td>${opts.technology}</td></tr>
        <tr><td style="font-weight:bold;background:#F5F1E9;border-left:3px solid #BF9B51">${l.version}</td><td>v${opts.version}</td></tr>
        <tr><td style="font-weight:bold;background:#F5F1E9;border-left:3px solid #BF9B51">${l.totalControls}</td><td>${opts.controls.length}</td></tr>
        <tr><td style="font-weight:bold;background:#F5F1E9;border-left:3px solid #BF9B51">${l.publishedDate}</td><td>${dateStr}</td></tr>
      </table>`;
  }

  if (sec.securityControls) {
    sn++;
    html += `<div class="page-break"><h1>${sn}. ${l.securityControls}</h1>`;
    grouped.forEach((group, gi) => {
      html += `<h2>${sn}.${gi + 1}. ${getCategoryLabel(group.category, opts.locale)}</h2>`;
      group.controls.forEach(ctrl => {
        html += `<div class="control-header">
          <span class="control-id">${ctrl.controlId}</span> &nbsp;
          <span class="control-title">${ctrl.title}</span>
          <span class="crit-badge crit-${ctrl.criticality}">${ctrl.criticality.toUpperCase()}</span>
        </div>`;
        html += `<table>`;
        if (ctrl.description) html += `<tr><td style="font-weight:bold;width:160px">${l.description}</td><td>${ctrl.description}</td></tr>`;
        if (ctrl.applicability) html += `<tr><td style="font-weight:bold">${l.applicability}</td><td>${ctrl.applicability}</td></tr>`;
        if (ctrl.securityRisk) html += `<tr><td style="font-weight:bold">${l.securityRisk}</td><td>${ctrl.securityRisk}</td></tr>`;
        if (ctrl.defaultBehaviorLimitations) html += `<tr><td style="font-weight:bold">${l.defaultBehavior}</td><td>${ctrl.defaultBehaviorLimitations}</td></tr>`;
        if (ctrl.automation) html += `<tr><td style="font-weight:bold">${l.automation}</td><td>${ctrl.automation}</td></tr>`;
        html += `<tr><td style="font-weight:bold">${l.confidence}</td><td>${Math.round(ctrl.confidenceScore * 100)}%</td></tr>`;
        html += `<tr><td style="font-weight:bold">${l.reviewStatus}</td><td>${ctrl.reviewStatus}</td></tr>`;
        if (ctrl.frameworkMappings.length > 0) {
          html += `<tr><td style="font-weight:bold">${l.frameworkMappings}</td><td>${ctrl.frameworkMappings.join(', ')}</td></tr>`;
        }
        html += `</table>`;
        if (ctrl.threatScenarios.length > 0) {
          html += `<div class="section-label">${l.threatModeling}</div>
            <table><tr><th>${l.threatName}</th><th>${l.strideCategory}</th><th>${l.likelihood}</th><th>${l.impact}</th></tr>`;
          ctrl.threatScenarios.forEach(ts => {
            html += `<tr><td>${ts.threatName}</td><td>${ts.strideCategory.replace(/_/g, ' ')}</td><td>${ts.likelihood.replace(/_/g, ' ')}</td><td>${ts.impact}</td></tr>`;
          });
          html += `</table>`;
        }
        if (ctrl.sourceTraceability.length > 0) {
          html += `<div class="section-label">${l.sourceTraceability}</div>
            <table><tr><th>${l.sourceName}</th><th>${l.excerpt}</th><th>${l.sourceConfidence}</th></tr>`;
          ctrl.sourceTraceability.forEach(s => {
            html += `<tr><td>${s.sourceName}</td><td style="font-style:italic">${s.excerpt.length > 120 ? s.excerpt.substring(0, 120) + '...' : s.excerpt}</td><td>${Math.round(s.confidence * 100)}%</td></tr>`;
          });
          html += `</table>`;
        }
      });
    });
    html += `</div>`;
  }

  if (sec.annexA) {
    sn++;
    html += `<div class="page-break"><h1>${sn}. ${l.annexA}</h1>
      <table><tr><th>${l.framework}</th><th>${l.controlCount}</th><th>${l.coveragePercent}</th></tr>`;
    fwCoverage.forEach(fw => { html += `<tr><td>${fw.framework}</td><td>${fw.count}</td><td>${fw.percent}%</td></tr>`; });
    html += `</table></div>`;
  }

  if (sec.annexB) {
    sn++;
    html += `<h1>${sn}. ${l.annexB}</h1>
      <table><tr><th>${l.sourceName}</th><th>${l.controlCount}</th><th>${l.sourceConfidence}</th></tr>`;
    srcIndex.forEach(s => { html += `<tr><td>${s.name}</td><td>${s.controlIds.length}</td><td>${s.avgConf}%</td></tr>`; });
    html += `</table>`;
  }

  html += `<div class="footer">${l.generatedBy} — ${dateStr}</div></body></html>`;

  const blob = new Blob(['\ufeff' + html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `baseline-${opts.projectName.replace(/\s+/g, '-').toLowerCase()}-v${opts.version}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
